export type Concept = {
  id: string;
  term: string;
  def: string;
  related: string[];
};

export type Flashcard = { front: string; back: string };

export type QuizQuestion = {
  prompt: string;
  options: string[];
  correct: number;
  explanation: string;
  quote: string;
};

export type MindMapColor = 'red' | 'orange' | 'yellow' | 'green' | 'blue' | 'purple' | 'pink';

export type MindMapBranch = {
  id: string;
  label: string;
  color: MindMapColor;
  conceptIds: string[];
};

export type MindMap = {
  hubLabel: string;
  hubColor: MindMapColor;
  branches: MindMapBranch[];
};

export type SampleDoc = {
  title: string;
  source: string;
  pages: number;
  summary: string[];
  concepts: Concept[];
  flashcards: Flashcard[];
  quiz: QuizQuestion[];
  quizId?: string;
  mindMap?: MindMap;
};

export const SAMPLE_DOC: SampleDoc = {
  title: 'Cellular Respiration & ATP Synthesis',
  source: 'Bio 101 · Chapter 9',
  pages: 4,
  summary: [
    "Cellular respiration is the metabolic pathway that converts chemical energy stored in nutrients into adenosine triphosphate (ATP), the cell's usable energy currency. The complete process unfolds in four coordinated stages — glycolysis, pyruvate oxidation, the citric acid cycle, and oxidative phosphorylation — each handing intermediates and electron carriers to the next.",
    'Glycolysis occurs in the cytoplasm and splits one glucose into two pyruvate molecules with a net gain of 2 ATP and 2 NADH. The pyruvate then enters the mitochondrial matrix, where it is oxidized to acetyl-CoA. The citric acid cycle (Krebs cycle) processes acetyl-CoA, producing additional NADH, FADH₂, and a small amount of GTP/ATP per turn.',
    'The bulk of ATP — roughly 28 of the ~32 produced per glucose — is generated by oxidative phosphorylation. Electrons donated by NADH and FADH₂ travel down the electron transport chain on the inner mitochondrial membrane, pumping protons into the intermembrane space. The resulting electrochemical gradient drives ATP synthase to phosphorylate ADP into ATP via chemiosmosis.',
  ],
  concepts: [
    { id: 'atp',          term: 'ATP',                       def: 'Adenosine triphosphate — the universal energy currency of cells. Energy is released when its terminal phosphate bond is hydrolyzed to form ADP + Pᵢ.', related: ['adp', 'synthase'] },
    { id: 'adp',          term: 'ADP',                       def: 'Adenosine diphosphate — the dephosphorylated form of ATP. Recycled back into ATP by ATP synthase.', related: ['atp', 'synthase'] },
    { id: 'nadh',         term: 'NADH',                      def: 'Reduced form of NAD⁺. Carries high-energy electrons from glycolysis and Krebs to the electron transport chain.', related: ['etc', 'krebs'] },
    { id: 'fadh2',        term: 'FADH₂',                     def: 'Reduced form of FAD. Donates electrons to Complex II of the electron transport chain, yielding fewer ATP than NADH.', related: ['etc', 'krebs'] },
    { id: 'glycolysis',   term: 'Glycolysis',                def: 'Cytoplasmic pathway that splits glucose into two pyruvate, yielding a net 2 ATP and 2 NADH per glucose.', related: ['pyruvate', 'nadh', 'glucose'] },
    { id: 'pyruvate-ox',  term: 'Pyruvate Oxidation',        def: 'Bridge step that converts pyruvate to acetyl-CoA inside the mitochondrial matrix, releasing CO₂ and reducing NAD⁺ to NADH.', related: ['pyruvate', 'krebs', 'matrix'] },
    { id: 'krebs',        term: 'Krebs Cycle',               def: 'Citric acid cycle. An eight-step cyclic pathway in the mitochondrial matrix that fully oxidizes acetyl-CoA, generating NADH, FADH₂, and GTP.', related: ['pyruvate-ox', 'nadh', 'fadh2', 'co2'] },
    { id: 'oxphos',       term: 'Oxidative Phosphorylation', def: 'Final stage where NADH/FADH₂ feed the electron transport chain and ATP synthase couples the resulting proton gradient to ATP synthesis.', related: ['etc', 'synthase', 'gradient'] },
    { id: 'pyruvate',     term: 'Pyruvate',                  def: 'Three-carbon end product of glycolysis. Transported into the mitochondrial matrix where it is oxidized to acetyl-CoA.', related: ['glycolysis', 'pyruvate-ox'] },
    { id: 'etc',          term: 'Electron Transport Chain',  def: 'Series of protein complexes (I–IV) on the inner mitochondrial membrane that transfer electrons from NADH/FADH₂ to O₂, pumping protons across the membrane.', related: ['nadh', 'fadh2', 'gradient', 'complex-iv'] },
    { id: 'synthase',     term: 'ATP Synthase',              def: 'Membrane-bound rotary enzyme that uses the proton gradient to phosphorylate ADP into ATP — the chemiosmotic engine of the cell.', related: ['gradient', 'atp', 'chemiosmosis'] },
    { id: 'gradient',     term: 'Proton Gradient',           def: 'Electrochemical gradient of H⁺ across the inner mitochondrial membrane. Stores potential energy that drives ATP synthase.', related: ['etc', 'synthase', 'chemiosmosis'] },
    { id: 'complex-iv',   term: 'Complex IV',                def: 'Cytochrome c oxidase — the terminal complex of the electron transport chain that transfers electrons to O₂, reducing it to water.', related: ['etc', 'oxygen', 'water'] },
    { id: 'glucose',      term: 'Glucose',                   def: 'Six-carbon sugar that enters cellular respiration as the primary fuel. Each molecule yields ~30–32 ATP under aerobic conditions.', related: ['glycolysis', 'aerobic'] },
    { id: 'oxygen',       term: 'Oxygen (O₂)',               def: 'Final electron acceptor in aerobic respiration. Reduced to water at Complex IV; without it the chain backs up and respiration stalls.', related: ['complex-iv', 'aerobic', 'water'] },
    { id: 'co2',          term: 'Carbon Dioxide (CO₂)',      def: 'Waste product of pyruvate oxidation and the Krebs cycle. Exhaled by the cell as carbons are stripped from organic intermediates.', related: ['pyruvate-ox', 'krebs'] },
    { id: 'water',        term: 'Water (H₂O)',               def: 'Formed at Complex IV when oxygen accepts electrons and protons. Roughly six water molecules per glucose are produced overall.', related: ['complex-iv', 'oxygen'] },
    { id: 'chemiosmosis', term: 'Chemiosmosis',              def: "Peter Mitchell's concept: an ion gradient across a membrane is harnessed to do work — here, driving ATP synthesis via ATP synthase.", related: ['gradient', 'synthase'] },
    { id: 'matrix',       term: 'Mitochondrial Matrix',      def: 'Innermost compartment of the mitochondrion. Hosts pyruvate oxidation and the Krebs cycle; bounded by the inner membrane.', related: ['pyruvate-ox', 'krebs'] },
    { id: 'aerobic',      term: 'Aerobic Respiration',       def: 'Oxygen-requiring respiration that runs the full pathway through oxidative phosphorylation, yielding ~30–32 ATP per glucose.', related: ['oxygen', 'glucose', 'oxphos'] },
    { id: 'fermentation', term: 'Fermentation',              def: 'Anaerobic recycling of NADH back to NAD⁺ when O₂ is scarce. Produces lactate (animals) or ethanol + CO₂ (yeast); only 2 ATP per glucose.', related: ['glycolysis', 'nadh'] },
  ],
  mindMap: {
    hubLabel: 'Cellular\nRespiration',
    hubColor: 'red',
    branches: [
      { id: 'stages',     label: 'Stages',         color: 'orange', conceptIds: ['glycolysis', 'pyruvate-ox', 'krebs', 'oxphos'] },
      { id: 'carriers',   label: 'Energy carriers', color: 'blue',   conceptIds: ['atp', 'adp', 'nadh', 'fadh2'] },
      { id: 'machinery',  label: 'Machinery',      color: 'purple', conceptIds: ['etc', 'synthase', 'gradient', 'complex-iv'] },
      { id: 'io',         label: 'Inputs · Outputs', color: 'green', conceptIds: ['glucose', 'oxygen', 'co2', 'water'] },
      { id: 'ideas',      label: 'Big ideas',      color: 'pink',   conceptIds: ['chemiosmosis', 'matrix', 'aerobic', 'fermentation'] },
    ],
  },
  flashcards: [
    { front: 'Net ATP yield per glucose from glycolysis alone?', back: '2 ATP (4 produced minus 2 invested), plus 2 NADH.' },
    { front: 'Where does the citric acid cycle take place?', back: 'The mitochondrial matrix — the inner compartment of the mitochondrion.' },
    { front: 'What molecule directly powers ATP synthase?', back: 'A proton (H⁺) gradient across the inner mitochondrial membrane.' },
    { front: 'Final electron acceptor in aerobic respiration?', back: 'Oxygen (O₂) — reduced to water at Complex IV.' },
    { front: 'Approx. total ATP yield per glucose?', back: 'About 30–32 ATP via complete aerobic respiration.' },
    { front: 'Which carrier yields more ATP per molecule, NADH or FADH₂?', back: 'NADH — it enters the chain at Complex I, pumping more protons.' },
  ],
  quiz: [
    { prompt: 'Which stage of cellular respiration produces the most ATP per glucose molecule?', options: ['Glycolysis', 'Pyruvate oxidation', 'Citric acid cycle', 'Oxidative phosphorylation'], correct: 3, explanation: 'Oxidative phosphorylation generates roughly 28 of the ~32 ATP per glucose by using the electron transport chain to build the proton gradient that drives ATP synthase.', quote: '"The bulk of ATP — roughly 28 of the ~32 produced per glucose — is generated by oxidative phosphorylation."' },
    { prompt: 'Where in the cell does glycolysis occur?', options: ['Mitochondrial matrix', 'Cytoplasm', 'Inner mitochondrial membrane', 'Nucleus'], correct: 1, explanation: 'Glycolysis is unique among respiration stages — it occurs in the cytoplasm and does not require oxygen or mitochondria.', quote: '"Glycolysis occurs in the cytoplasm and splits one glucose into two pyruvate molecules…"' },
    { prompt: 'What is the net energy yield of glycolysis per glucose?', options: ['2 ATP and 2 NADH', '4 ATP and 2 NADH', '2 ATP only', '6 ATP and 2 FADH₂'], correct: 0, explanation: 'Glycolysis invests 2 ATP and produces 4, for a net of 2 ATP plus 2 NADH electron carriers.', quote: '"…with a net gain of 2 ATP and 2 NADH."' },
    { prompt: 'Which enzyme directly catalyzes the phosphorylation of ADP into ATP using a proton gradient?', options: ['Hexokinase', 'Cytochrome c oxidase', 'ATP synthase', 'Pyruvate dehydrogenase'], correct: 2, explanation: 'ATP synthase is a rotary enzyme embedded in the inner mitochondrial membrane that harnesses proton flow to add phosphate to ADP.', quote: '"…drives ATP synthase to phosphorylate ADP into ATP via chemiosmosis."' },
    { prompt: 'In which cellular compartment does the citric acid cycle take place?', options: ['Cytoplasm', 'Inner membrane', 'Intermembrane space', 'Mitochondrial matrix'], correct: 3, explanation: 'The citric acid (Krebs) cycle runs entirely in the mitochondrial matrix, where acetyl-CoA enters after pyruvate oxidation.', quote: '"The citric acid cycle (Krebs cycle) processes acetyl-CoA…"' },
    { prompt: 'What molecule serves as the final electron acceptor in the electron transport chain?', options: ['NAD⁺', 'CO₂', 'O₂', 'Pyruvate'], correct: 2, explanation: 'Oxygen accepts the spent electrons at Complex IV and is reduced to water — this is why aerobic respiration requires O₂.', quote: '"Electrons donated by NADH and FADH₂ travel down the electron transport chain…"' },
    { prompt: 'Which of these is NOT produced during the citric acid cycle?', options: ['NADH', 'FADH₂', 'GTP/ATP', 'Pyruvate'], correct: 3, explanation: 'Pyruvate is consumed before the cycle (oxidized to acetyl-CoA). The cycle itself produces NADH, FADH₂, and GTP/ATP.', quote: '"…producing additional NADH, FADH₂, and a small amount of GTP/ATP per turn."' },
    { prompt: 'What drives proton movement across the inner mitochondrial membrane during oxidative phosphorylation?', options: ['ATP hydrolysis', 'Electron transport', 'Glucose oxidation', 'Diffusion of CO₂'], correct: 1, explanation: 'Energy released as electrons fall through Complexes I, III, and IV is used to actively pump protons against their gradient.', quote: '"…pumping protons into the intermembrane space."' },
    { prompt: 'How many pyruvate molecules are produced from one glucose during glycolysis?', options: ['One', 'Two', 'Three', 'Four'], correct: 1, explanation: 'Glycolysis splits the six-carbon glucose into two three-carbon pyruvate molecules.', quote: '"…splits one glucose into two pyruvate molecules…"' },
    { prompt: 'Which term best describes the coupling of the proton gradient to ATP synthesis?', options: ['Glycolysis', 'Chemiosmosis', 'Fermentation', 'Phosphorylation cascade'], correct: 1, explanation: "Chemiosmosis is Peter Mitchell's term for using an ion gradient (here, H⁺) across a membrane to drive ATP production.", quote: '"…drives ATP synthase to phosphorylate ADP into ATP via chemiosmosis."' },
  ],
};

export type RecentDoc = {
  id: string;
  title: string;
  meta: string;
  when: string;
  score: string | null;
};

export const RECENT_DOCS: RecentDoc[] = [
  { id: '1', title: 'Cellular Respiration & ATP Synthesis', meta: 'Bio 101 · 4 pages', when: 'Just now',  score: null },
  { id: '2', title: 'Supply & Demand Equilibrium',          meta: 'Econ 110 · 6 pages', when: '2 days ago', score: '8/10' },
  { id: '3', title: 'The French Revolution: Causes',        meta: 'Hist 220 · 9 pages', when: 'Last week',  score: '9/10' },
  { id: '4', title: 'Linear Algebra · Eigenvalues',         meta: 'Math 240 · 5 pages', when: 'Apr 18',     score: '6/10' },
];

export const CONCEPT_LAYOUT: Record<string, { x: number; y: number }> = {
  atp:        { x: 0.50, y: 0.50 },
  synthase:   { x: 0.34, y: 0.34 },
  gradient:   { x: 0.22, y: 0.55 },
  etc:        { x: 0.32, y: 0.78 },
  nadh:       { x: 0.55, y: 0.83 },
  fadh2:      { x: 0.74, y: 0.74 },
  krebs:      { x: 0.80, y: 0.50 },
  pyruvate:   { x: 0.74, y: 0.25 },
  glycolysis: { x: 0.55, y: 0.16 },
  adp:        { x: 0.66, y: 0.40 },
};
